---
- name: Create an ubuntu container on all servers & mount a volume
  hosts: all
  tasks:
    - name: Create an ubuntu container on all servers & mount a volume
      docker_container:
        name: myubuntu
        image: ubuntu
        interactive: yes
        tty: yes
        volumes:
          - /data
...
