---
- name: Configure tomcat using child playbooks and host scope variables
  hosts: all
  tasks:
    - name: Call multiple child playbooks
      include_tasks: "{{item}}"
      with_items:
        - install_tomcat.yml
        - copy_tomcatusers.yml
        - change_port.yml
        - restart_tomcat.yml
        - pause.yml
        - check_tomcat_response.yml
...
