---
- name: Create user
  hosts: 172.31.23.42
  tasks:
    - name: User creation
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
        home: "{{d}}"
        shell: "{{e}}"
        comment: "{{f}}"
...
