---
- name: Install / uninstall software applications
  hosts: all
  tasks:
    - name: Install / uninstall
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree , b: present , c: no}
        - {a: git , b: present, c: no}
...
