---
- name: Configuring tomcat
  hosts: all
  tasks:
    - name: Install tomcat
      apt:
        name: tomcat10
        state: present
        update_cache: yes
    - name: Install tomcat10-admin
      apt:
        name: tomcat10-admin
        state: present
    - name: copy tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: Change port of tomcat10 from 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: Restart tomcat10
      service:
        name: tomcat10
        state: restarted
    - name: Pause for 30 seconds
      pause:
        seconds: 30
    - name: Check tomcat on server1
      uri:
        url: http://172.31.25.77:9090
        status_code: 200
    - name: Check tomcat10 on server2
      uri:
        url: http://172.31.29.183:9090
        status_code: 200
