---
- name: Configure apache2/httpd based on linux flavour
  hosts: all
  tasks:
    - name: Install apache2 on ubuntu servers
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution=="Ubuntu"
    - name: Install httpd on RHEL server
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution=="RedHat"
    - name: Edit index.html file
      copy:
        content: "Hello"
        dest: /var/www/html/index.html
    - name: Restart apache2 on ubuntu servers
      service:
        name: apache2
        state: restarted
      when: ansible_distribution=="Ubuntu"
    - name: Restart httpd on RHEL server
      service:
        name: httpd
        state: restarted
      when: ansible_distribution=="RedHat"
    - name: Check apache/httpd response on all servers
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.11.248
        - http://172.31.25.77
        - http://172.31.29.183
...
