---
- name: Error handling or exception handling
  hosts: all
  tasks:
    - block:
        - name: Install git on ubuntu servers using ap
          apt:
            name: git
            state: present
            update_cache: yes
      rescue:
       - name: Install git on RHEL using yum
         yum:
           name: git
           state: present
           update_cache: yes
      always:
        - name: Display success message
          debug:
            msg: "Git installation is success"
...
