---
- name: Create a empty folder and download jenkins.war file into it
  hosts: all
  tasks:
    - name: Create a empty folder
      file:
        name: /tmp/jenkins
        state: directory
    - name: Download jenkins.war file
      get_url:
        url: https://get.jenkins.io/war-stable/2.462.3/jenkins.war
        dest: /tmp/jenkins
    - name: Change permissions of the jenkins.war file
      file:
        name: /tmp/jenkins/jenkins.war
        mode: 700
...
