---
- name: Implementing play scope variables
  hosts: all
  vars:
    a: tomcat10
    b: present
    c: yes
    d: restarted
  tasks:
    - name: Install software apps
      apt: 
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
    - name: Restart
      service:
        name: "{{a}}"
        state: "{{d}}"
        
...
