---
- name: Implementing global scope variables
  hosts: all
  tasks:
    - name: Install / uninstall software apps
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...
